### ISSUE TITLE
Issue of Google Sans Mono being non-existent

### ISSUE THREAD

**Issue by ghost** [mehant-kr/Google-Sans-Mono#1]
Google Sans (infact it's actually Product Sans) there exists only proportional variant. There's no existence of Monospace. I donno which font this is, but I'm sure this is rip off of some other monospaced typeface.

**Comment by mehant-kr** [comment]
Hello @pc00per,
I was browsing through dart documentation and I liked the font in [here](https://dart.dev/guides/language/concurrency). I searched about it and I got "Google Sans" and it definitely looks like monospaced. I got these fonts from [here](https://fonts.googleapis.com/css2?family=Google+Sans+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700), I converted it to ttf and adjusted weights of few of them using [fontlab](https://www.fontlab.com/). Then I thought it could be useful to people so I placed it here. I certainly don't know about it's existance, google has never reveled it I suppose, that's why it's not available anywhere.

**Comment by ghost** [comment]
> Hello @pc00per, I was browsing through dart documentation and I liked the font in [here](https://dart.dev/guides/language/concurrency). I searched about it and I got "Google Sans" and it definitely looks like monospaced. I got these fonts from [here](https://fonts.googleapis.com/css2?family=Google+Sans+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700), I converted it to ttf and adjusted weights of few of them using [fontlab](https://www.fontlab.com/). Then I thought it could be useful to people so I placed it here. I certainly don't know about it's existance, google has never reveled it I suppose, that's why it's not available anywhere.

Google never had monospaced Product Sans typeface officially (although your link shows that it do exist), I don't really think it's actually a sans typeface at all.
Look at the lowercase 'i', it's clearly a Serif.

**Comment by mehant-kr** [comment]
Look at lower case 'i' in  [Nono Sans Mono](https://fonts.google.com/noto/specimen/Noto+Sans+Mono?query=noto+sans+mono) and in [DejaVu Sans Mono](https://en.wikipedia.org/wiki/DejaVu_fonts). it looks like this `i`. 
I don't think serif is used in codes. 
In [Sans-serif](https://en.wikipedia.org/wiki/List_of_sans_serif_typefaces) typeface 'i' looks pretty different in it. Almost every 'i' in [Monospaced](https://en.wikipedia.org/wiki/List_of_monospaced_typefaces) typeface looks alike.
So in shot, I think the name 'sans mono' is fair.

**Comment by ghost** [comment]
> Look at lower case 'i' in [Nono Sans Mono](https://fonts.google.com/noto/specimen/Noto+Sans+Mono?query=noto+sans+mono) and in [DejaVu Sans Mono](https://en.wikipedia.org/wiki/DejaVu_fonts). it looks like this `i`. I don't think serif is used in codes. In [Sans-serif](https://en.wikipedia.org/wiki/List_of_sans_serif_typefaces) typeface 'i' looks pretty different in it. Almost every 'i' in [Monospaced](https://en.wikipedia.org/wiki/List_of_monospaced_typefaces) typeface looks alike. So in shot, I think the name 'sans mono' is fair.

Oh okay. Haven't noticed in others.
Tq for reverse engineering a non existent font btw. 😁
